#!/usr/bin/env ruby

module Scrooge
  extend self

  BLACK="\033[0;30m"
  RED="\033[0;31m"
  GREEN="\033[0;32m"
  YELLOW="\033[0;33m"
  BLUE="\033[0;34m"
  PURPLE="\033[0;35m"
  CYAN="\033[0;36m"
  WHITE="\033[0;37m"

  LIGHT_BLACK="\033[1;30m"
  LIGHT_RED="\033[1;31m"
  LIGHT_GREEN="\033[1;32m"
  LIGHT_YELLOW="\033[1;33m"
  LIGHT_BLUE="\033[1;34m"
  LIGHT_PURPLE="\033[1;35m"
  LIGHT_CYAN="\033[1;36m"
  LIGHT_WHITE="\033[1;37m"

  def mcduck
    hat_top = BLUE
    hat_rim = BLUE
    hat_inner = WHITE
    eye = WHITE
    eyeball = GREEN
    feather = WHITE
    beak = YELLOW
    speech = GREEN

    <<-SCROOGE
                     #{hat_top}$$$$$$$$$$$$$$$$$$$$$$
                   $$$$$$$$$$$$$$$$$$$$$$$$
                 $$$$    $$$$$$$$$$$$$$$$$$$$
                $$$$$     $$$$$$$$$$$$$$$$$$$
              $$$$$$$$     $$$$$$$$$$$$$$$$$$
            $$$$$$$$$$$     $$$$$$$$$$$$$$$
           $$$$$$$$$$$$$     $$$$$$$$$$$$$$
          $$$$$$$$$$$$$$$     $$$$$$$$$$$$$
            $$$$$$$$$$$$$$    $$$$$$$$$$$$$
              $$$$$$$$$$$$$$$$$$$$$$$$$$$$$
                $$$$$$$$$$$$$$$$$$$$$$$$$$$      #{hat_rim}$$$$$$
                 #{hat_top}$$$$$$$$$$$$          $$$$   #{hat_rim}$$$$   $$$
                #{hat_top}$$$$$$$                  $$    #{hat_rim}$$$$    $$$
           #{hat_rim}$$$$$$$$$$$$$$$$$$          $$$$$$$$   $$$$  $
        $$$$               $$$$$$$$$$$$$       $$$$$$$$$$
      $$$$    #{hat_inner}$$$$$$$$$$                   $$$$$$$$$$$$
      #{hat_rim}$$   #{hat_inner}$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ $$$$$$$$$$
     #{hat_rim}$  #{hat_inner}$$$$$$$$$$$$$$$$$$$$$                   $$$$$$
     #{hat_rim}$  #{hat_inner}$$$$$$$$$$$$$$$$$                       $$$$
     #{hat_rim}$  #{hat_inner}$$$$$$$$$$$$$$                       #{eye}$$$$$
      #{hat_rim}$$  #{hat_inner}$$$$$$$$$$           #{eye}$$$$$       $$$    $$    #{speech_bubble_line_1}
        #{hat_inner}$$$$$$$$$$$$         #{eye}$$$   $$$     $$$    $$   #{speech_bubble_line_2}
          #{hat_inner}$$$$$$$$           #{eye}$      $$$$     $      $$#{speech_bubble_line_3}
         #{feather}$$  #{hat_inner}$$$$$           #{eye}$        $      $#{eyeball}$$$   #{eye}$$ #{speech_bubble_line_4}
           #{feather}$$  #{hat_inner}$$$  #{feather}$$$$     #{eye}$        $$$    $#{eyeball}$$$$  #{eye}$$ #{beak}$$$$
        #{feather}$$$$$$$   $$         #{eye}$  #{eyeball}$$$$  #{eye}$$$    $#{eyeball}$$$$  #{eye}$$#{beak}$$   $$
      #{feather}$$$       $$$   #{beak}$$$    #{eye}$#{eyeball}$$$$$$$  #{eye}$$  $$$#{eyeball}$$$$  #{eye}$$#{beak}$    $$
      #{feather}$$   $$   $$  #{beak}$$$$$$$  #{eye}$#{eyeball}$$$$$$$$ #{eye}$$$$$$$$$$$$$$$#{beak}$    $$
      #{feather}$$ $$$        #{beak}$$   $$  #{eye}$#{eyeball}$$$$$$$$   #{eye}$$     $$    #{beak}$$$$$$$$$
       #{feather}$$$$  $$     #{beak}$$   $$    #{eye}$#{eyeball}$$$$$$ #{eye}$$$$     #{beak}$$$$$$$$$     $$
       #{feather}$$$ $$   $$$$#{beak}$$ $$$$$$   #{eye}$$$$$$$$$$#{beak}$$$ #{beak}$$$$$$$    $$$  $$
       #{feather}$$  $$  $$$$$#{beak}$$ $$$ $$$$$$$$$$$$$$$$$$$$$      $$$   $$$$
        #{feather}$$$$$$$$    #{beak}$$$$ $$  $$$$$$$$$$$          $$$$ $$$$$$$
                    $$$$   $$                   $$$$$$$$$
                      $$$   $$$$$            $$$$$$$ $$$
                       $$$$  $$$$$$$     $$$$$$$$$$$$$
                        $$$$$   $$$$$$$$$$$$$$$$$$  $$
                         $$$$$$   $$$$$$$$$$$$$$  $$
                           $$$$$     $$$$$$$$$$$  $$
                             $$$$$$$        $$$$$$$$
                               $$$$$$$$$$$$$$$$ $$
                                 $$$$$$$$$$$$#{WHITE}
    SCROOGE
  end

  def speak
    system `say -v Oliver #{text}`
  end

  private

  def text
    @text ||= filtered_text(ARGV.first) || random_text
  end

  def filtered_text(text)
    return unless text
    matches = text.match(/([^-]+)/)
    matches.captures.first if matches.captures
  end

  def has_text?
    text && !text.length.zero?
  end

  def padding
    ' ' * 5
  end

  def speech_bubble_line_1
    padding + '_' * text.length if has_text?
  end

  def speech_bubble_line_2
    "#{padding}/" + (' ' * text.length) + '\\' if has_text?
  end

  def speech_bubble_line_3
    "#{padding}< #{text} |" if has_text?
  end

  def speech_bubble_line_4
    "#{padding}\\"+ ('_' * text.length) + '/' if has_text?
  end

  def random_text
    [
      'a penny saved is a penny earned',
      'the beagle boys are after me number one dime',
      'Magica DeSpell, I should have known youd be behind this!',
      'i am smarter than the smarties and tougher than the toughies',
      'boys, how are you going to profit if your operative costs are so high?',
      'im scrooge mcduck',
      'GAH! Me money!',
      'Curse me kilts! Me money bin alarm! Quick, Duckworth, get the limo!',
      'Not the Beagle Boys again... if the think they can get between Scrooge McDuck and his three cubic acres of cash, theyve got another thing coming',
      'Curse me kilts! One false move, and Im a roast duck!',
      'Launchpad, were you dropped on your head much as a child?',
      'I can feel all those diamonds singing to me. And its a right pretty song, too!',
      'Heavenly heather! The genie in the magic lamp! The fortunes I could own! I could have the worlds biggest diamond! No! The worlds biggest diamond mine! No-no! All the diamond mines! No! The entire mining industry! Yes, yes, yes! I can see that this is going to take some careful thought.',
      'Here I sit in this big lonely dump, waiting for Christmas to pass! Bah! That silly season when everybody loves everybody else! A Curse on it! Me — Im different! Everybody hates me, and I hate everybody!',
    ].sample
  end
end

puts Scrooge.mcduck
Scrooge.speak

